export const data = [
    {
        question: 'IOS geliştirme için kullanılan araç ',
        a:'buzdolabı',
        b:'fırın',
        c:'ördek',
        d:'macbook',
        correct:'d',
    },
    {
        question: 'at arabasını ne çeker',
        a:'araba',
        b:'motor',
        c:'at',
        d:'uçan halı',
        correct:'c',
    },
    {
        question: 'witcherın aşkı kimdir',
        a:'Yennefer',
        b:'Triss',
        c:'Roach',
        d:'Lambert',
        correct:'a',
    },
    {
        question: 'css nasıl öğrenilir',
        a:'Tanrı bahşeder',
        b:'Vahiy yoluyla',
        c:'Tiktok ile',
        d:'İçine doğar',
        correct:'d',
    },
    {
        question: '2020 en popüler hastalığı nedir',
        a:'dolar',
        b:'aptallık',
        c:'koyunl olmak',
        d:'covid',
        correct:'a',
    },
    {
        question: 'array neye benzer',
        a:'{deneme}',
        b:'<deneme>',
        c:'deneme &&deneme',
        d:'[deneme]',
        correct:'d',
    },
]